#!/bin/sh

GEOMETRY="/tmp/.cocon.geometry"
CNFFILE="/tmp/.cocon.cnf"

if [ -e $CNFFILE ];
then
  . $CNFFILE
fi

# first, copy settings from skel.
su -c "cp -R /etc/skel/.config/ /home/xuser" xuser
su -c "cp /etc/skel/.profile /home/xuser" xuser

exit 0
