#!/bin/sh

# Classic opencocon init : remain is here.

DEFCONF="/usr/share/cocon/default.cnf"
SECCONF="/mnt/union/mnt/realroot/cocon.cnf"
SECCONF_EXTREME="/cocon.cnf"
CONF_MOUNT="/mnt/cfg"
CNFFILE="/tmp/.cocon.cnf"
CNFFILE_BOOTDRIVE="/tmp/.cocon.cnf.bootdrive"
DISKSTATS_TMP="/var/volatile/tmp/.cocon.diskstats"
CNF_NM_FILE_MOVETO="/tmp/.cocon.cnf.files/nm/"
CNF_NM_FILE_MOVETO_BOOTDRIVE="/tmp/.cocon.cnf.files/nm.bootdrive/"
COPYTORAM_AFTER_INITRD="/mnt/oldroot/mnt/copytoram"
CNF_LOGFILE="/var/log/cocon-cnf.log"

read_args() {
    [ -z "$CMDLINE" ] && CMDLINE=`cat /proc/cmdline`
    for arg in $CMDLINE; do
        optarg=`expr "x$arg" : 'x[^=]*=\(.*\)'`
        case $arg in
            debug) set -x
                COCON_DEBUG=1
                export COCON_DEBUG
                echo "COCON_DEBUG=1"  >> $CNFFILE
                ;;
            forcefb1|forcefb2|forcefb3|forcefb)
                echo "COCON_FORCEFB=1"  >> $CNFFILE
                ;;
            forcesvga)
                echo "COCON_FORCESVGA=1" >> $CNFFILE
                ;;
            dropbear)
                COCON_DROPBEAR=1
                export COCON_DROPBEAR
                echo "COCON_DROPBEAR=1"  >> $CNFFILE
                ;;
            stopbeforex)
                COCON_XDEBUG=1
                export COCON_XDEBUG
                echo "COCON_XDEBUG=1"  >> $CNFFILE
                ;;
            delayreadcfg)
                COCON_DELAY_CFG=1
                export COCON_DELAY_CFG
                echo "COCON_DELAY_CFG=1"  >> $CNFFILE
                ;;
        esac
    done
}


read_args


# After parsing setting file, read .cocon.cnf
if [ -e $CNFFILE ];
then
  . $CNFFILE
fi


# NetworkManager IPv6 fix
ln -sf /var/lib/dbus/machine-id /etc/machine-id

# Keymap (TODO)
if [ -z $COCON_KBD_CONSOLE ];
then
  COCON_KBD_CONSOLE="jp106"
fi

/usr/bin/loadkeys $COCON_KBD_CONSOLE

# Timezone (TODO)
ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# If /var/log is not folder, recreate it.
# (only for coconrpi?)
if [ ! -d "/var/log/" ];
then
  rm -rf /var/log/
  mkdir -p /var/log/
fi

# Hostname
hostname tiny$RANDOM

