#!/bin/sh

# Classic opencocon init : remain is here.

DEFCONF="/usr/share/cocon/default.cnf"
SECCONF="/mnt/union/mnt/realroot/cocon.cnf"
SECCONF_EXTREME="/cocon.cnf"
CONF_MOUNT="/mnt/cfg"
CNFFILE="/tmp/.cocon.cnf"
CNFFILE_BOOTDRIVE="/tmp/.cocon.cnf.bootdrive"
DISKSTATS_TMP="/var/volatile/tmp/.cocon.diskstats"
CNF_NM_FILE_MOVETO="/tmp/.cocon.cnf.files/nm/"
CNF_NM_FILE_MOVETO_BOOTDRIVE="/tmp/.cocon.cnf.files/nm.bootdrive/"
COPYTORAM_AFTER_INITRD="/mnt/oldroot/mnt/copytoram"
CNF_LOGFILE="/var/log/cocon-cnf.log"


# After parsing setting file, read .cocon.cnf
if [ -e $CNFFILE ];
then
  . $CNFFILE
fi

# Keymap (TODO)
if [ -z $COCON_KBD_CONSOLE ];
then
  COCON_KBD_CONSOLE="jp106"
fi

/usr/bin/loadkeys $COCON_KBD_CONSOLE

# Timezone (TODO)
ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

