#!/bin/sh

# opencocon power-off script
CNFFILE="/tmp/.cocon.cnf"


# Read .cocon.cnf
if [ -e $CNFFILE ];
then
  . $CNFFILE
fi


if [ -n "$COCON_DEBUG" ];
then
  echo "DEBUG: before shutdown."
  /bin/sh
fi


if [ -n "$BOOT_FS" ];
then
  # have union-boot flag : Run cleanup script to eject Live CD.
  cd /mnt/oldroot
  . ./sbin/clean <dev/console >dev/console 2>&1

fi


