#!/bin/sh

# mount missing volatile directories

#mount -t tmpfs none /var/volatile
#mkdir /var/volatile/tmp

if [ ! -d /var/volatile/log ];
then
  mkdir -p /var/volatile/log
fi

# TODO : create on base-files.
mkdir -p /var/volatile/run
mkdir -p /var/volatile/lock
mkdir -p /var/volatile/run
mkdir -p /var/volatile/run/dbus
mkdir -p /var/volatile/lock

# If /var/log is not folder, recreate it.
# (only for coconrpi?)
if [ ! -d "/var/log/" ];
then
  rm -rf /var/log/
  mkdir -p /var/log/
fi

# make /var/run/dbus#
if [ ! -d "/var/run/dbus" ];
then
  mkdir -p /var/run/dbus
fi

# NetworkManager IPv6 fix
ln -sf /var/lib/dbus/machine-id /etc/machine-id

