#!/bin/bash

# opencocon VNC Launcher

if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ $COCON_VNC_HOST ];
then
    
  # libvncviewer
  exec coconvnc $COCON_VNC_HOST
 
else
  echo "Please specify HOST."
fi

