#!/bin/sh

USERN=/tmp/.cocon.menu.usern
SCRX=/tmp/.cocon.freerdp.x
SCRY=/tmp/.cocon.freerdp.y

# opencocon FreeRDP Launcher
if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ -z $COCON_RDP_RDPFILE ];
then
  if [ -z $COCON_RDP_HOST ];
  then
    echo "Error: please spcify COCON_RDP_HOST."
    exit 1
  else

    # User name
    if [ -z $COCON_RDP_USER ];
    then
      dialog --inputbox "Enter login username (require for login)" 8 40 2>$USERN
      COCON_RDP_USER="`cat $USERN`"
    fi

    if [ -n "`echo $COCON_RDP_USER | grep [[:space:]]`" ];
    then
      OPTION="$OPTION \"/u:$COCON_RDP_USER\" "
    else
      OPTION="$OPTION /u:$COCON_RDP_USER "
    fi

    # Domain name
    if [ $COCON_RDP_DOMAIN ];
    then
      if [ -n "`echo $COCON_RDP_DOMAIN | grep [[:space:]]`" ];
      then
        OPTION="$OPTION \"/d:$COCON_RDP_DOMAIN\" "
      else
        OPTION="$OPTION /d:$COCON_RDP_DOMAIN "
      fi
    fi

   # TODO : password

  fi

else
  # .rdp file is present: ignore COCON_RDP_HOST etc.
#  OPTION="$OPTION $COCON_RDP_RDPFILE "
  echo "WARNING: RDPFILE is disabled."
fi


# Remote FX
# TODO : Redefine Settings...
if [ "$COCON_RDP_RFX" = "1" ];
then
  OPTION="$OPTION /rfx /multimedia:sys:alsa /microphone:sys:alsa "
else
  OPTION="$OPTION "  # TODO : /network:modem
fi


if [ "$COCON_RDP_MODEM" = "1" ];
then
  OPTION="$OPTION /network:modem "
fi

# Calclate screen size
expr $( xrandr |grep \* |awk '{print $1}' | cut -d 'x' -f 1 ) - 25 > $SCRX
expr $( xrandr |grep \* |awk '{print $1}' | cut -d 'x' -f 2 ) - 20 > $SCRY

# finally, add HOSTNAME
OPTION="$OPTION /v:$COCON_RDP_HOST +smart-sizing /size:$(cat $SCRX)x$(cat $SCRY) /sound:sys:alsa"

pw_count=0

while :
do

  echo "=========================================="
  echo "    PASSWORD is not shown in console."
  echo "=========================================="

  xfreerdp $OPTION
  retr=$?

  if [ "$retr" != "131" ];
  then
    break
  fi

  # exceed the retry count?
  pw_count=` expr $pw_count + 1 `
  if [ $pw_count -gt 4 ];
  then
    break
  fi
done

