#!/bin/bash

# opencocon VNC Launcher

if [ -e /tmp/.cocon.cnf ];
then
  . /tmp/.cocon.cnf
fi
if [ -e /tmp/.cocon.cnf.part ];
then
  . /tmp/.cocon.cnf.part
fi

if [ $COCON_VNC_HOST ];
then

    # Username
    if [ $COCON_VNC_USER ];
    then
      OPTION="$OPTION -u $COCON_VNC_USER "
    fi
    
  # libvncviewer
  exec coconvnc $OPTION $COCON_VNC_HOST
 
else
  echo "Please specify HOST."
fi

