#!/bin/sh

CNF_NM_FILE_MOVETO="/tmp/.cocon.cnf.files/nm/"

# opencocon userland init

# special machines
/usr/bin/cocon-spmachine

# Copy NetworkManager settings
if [ -d $CNF_NM_FILE_MOVETO ];
then
  cp $CNF_NM_FILE_MOVETO/* /etc/NetworkManager/system-connections/
fi

# Run Menu
su -c 'cocon-startx' xuser
retr=$?

# Power off runs on .profile!
cocon-poweroff

